"""Initial schema: telegram_sessions, monitored_channels, indexing_log, search_analytics

Revision ID: d62557355ac3
Revises: 
Create Date: 2026-01-30 23:59:15.485403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd62557355ac3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('detected_category', sa.String(length=50), nullable=True),
    sa.Column('filters_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('clicked_result', sa.String(length=255), nullable=True),
    sa.Column('searched_at', sa.DateTime(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_analytics_user_id'), 'search_analytics', ['user_id'], unique=False)
    op.create_table('telegram_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_sessions_session_name'), 'telegram_sessions', ['session_name'], unique=True)
    op.create_table('monitored_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=False),
    sa.Column('total_indexed', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['telegram_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_channels_username'), 'monitored_channels', ['username'], unique=True)
    op.create_table('indexing_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('router_tokens', sa.Integer(), nullable=True),
    sa.Column('specialist_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['monitored_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexing_log_document_id'), 'indexing_log', ['document_id'], unique=True)
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_table_pkey'))
    )
    op.drop_index(op.f('ix_indexing_log_document_id'), table_name='indexing_log')
    op.drop_table('indexing_log')
    op.drop_index(op.f('ix_monitored_channels_username'), table_name='monitored_channels')
    op.drop_table('monitored_channels')
    op.drop_index(op.f('ix_telegram_sessions_session_name'), table_name='telegram_sessions')
    op.drop_table('telegram_sessions')
    op.drop_index(op.f('ix_search_analytics_user_id'), table_name='search_analytics')
    op.drop_table('search_analytics')
    # ### end Alembic commands ###
