"""drop clicked_listing_id from search_analytics

Revision ID: 78cbfeb3144c
Revises: 0001_baseline
Create Date: 2026-02-17 00:42:39.539451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cbfeb3144c'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_analytics', 'clicked_listing_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_analytics', sa.Column('clicked_listing_id', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
